site_name: The Tower Wiki
site_url: https://pingcheng.github.io/the-tower-wiki
theme:
  name: material
  custom_dir: overrides
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.share
markdown_extensions:
  - tables
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  analytics:
    provider: google
    property: G-GDJL638KWC
    feedback:
      title: 'Was this page helpful?'
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/pingcheng/the-tower-wiki/issues/new?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>
plugins:
  - glightbox
  - search
  - tags
  - git-committers:
      repository: pingcheng/the-tower-wiki
      branch: main
      exclude:
        - index.md

nav:
  - Modules:
      - Sub-module effects: 'module/sub-stats.md'
      - Merging: 'module/merge.md'
      - Legendary modules: 'module/legendary-modules.md'
  - Lab:
      - Cell costs: 'lab/cell-cost.md'
  - Tournament:
      - Rewards v24-v25: 'tournament/v24-25-rewards.md'
  - Extra:
      - Thorn damage table: 'misc/thorn-to-boss.md'